/*
 important*/
(function(g){var e=function(){};e.test=document.createElement("div");e.randomiseArray=function(c){var h=[],d=[],m;for(m=0;m<c;m++)h[m]=m;for(m=0;m<c;m++){var n=Math.round(Math.random()*(h.length-1));d[m]=h[n];h.splice(n,1)}return d};e.sortArray=function(c,h){var d,m=c.length,n=[];for(d=0;d<m;d++)n[d]=c[h[d]];return n};e.keysrt=function(c,h,d){var m=1;d&&(m=-1);return c.sort(function(n,t){var y=n[h],p=t[h];return m*(y<p?-1:y>p?1:0)})};e.keysrt2=function(c,h,d,m){var n=1;m&&(n=-1);return c.sort(function(t,
y){var p=t[h][d],v=y[h][d];return n*(p<v?-1:p>v?1:0)})};e.isEmpty=function(c){return 0==c.replace(/^\s+|\s+$/g,"").length};e.checkKey=function(c){return c.replace(/[^0-9a-zA-Z_-\s(),]/g,"")};e.stripSlashes=function(c){c=c.replace(/\\/g,"/");c=c.replace(/\\'/g,"'");c=c.replace(/\\"/g,'"');c=c.replace(/\\0/g,"\x00");return c=c.replace(/\\\\/g,"\\")};e.filterAllowedChars=function(c){var h=c.length,d="",m;for(m=0;m<h;m++){var n=c.charAt(m).toLowerCase();"\\"==n&&(n="/");var t=n.charCodeAt(0);if(97<=t&&
122>=t||48<=t&&57>=t||0<="_-".indexOf(n))d+=n}return d};e.selectText=function(c){var h=document;c=h.getElementById(c);if(h.body.createTextRange)h=h.body.createTextRange(),h.moveToElementText(c),h.select();else if(g.getSelection){var d=g.getSelection();h=h.createRange();h.selectNodeContents(c);d.removeAllRanges();d.addRange(h)}};e.getVideoFormat=function(){var c=document.createElement("video");if(c.canPlayType){if("probably"==c.canPlayType("video/mp4")||"maybe"==c.canPlayType("video/mp4"))var h=".mp4";
else if("probably"==c.canPlayType("video/ogg")||"maybe"==c.canPlayType("video/ogg"))h=".ogg";else if("probably"==c.canPlayType("video/webm")||"maybe"==c.canPlayType("video/webm"))h=".webm";return h}};e.videoSupport=function(){return!!document.createElement("video").canPlayType};e.canPlayVorbis=function(){var c=document.createElement("video");return!(!c.canPlayType||!c.canPlayType('video/ogg; codecs="theora, vorbis"').replace(/no/,""))};e.canPlayMp4=function(){var c=document.createElement("video");
return!(!c.canPlayType||!c.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"').replace(/no/,""))};e.canPlayWebM=function(){var c=document.createElement("video");return!(!c.canPlayType||!c.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/no/,""))};e.audioSupport=function(){return!!document.createElement("audio").canPlayType};e.canPlayMp3=function(){var c=document.createElement("audio");return!(!c.canPlayType||!c.canPlayType("audio/mpeg;").replace(/no/,""))};e.canPlayWav=function(){var c=
document.createElement("audio");return!(!c.canPlayType||!c.canPlayType("audio/wav;").replace(/no/,""))};e.canPlayAac=function(){var c=document.createElement("audio");return!(!c.canPlayType||!c.canPlayType("audio/aac;").replace(/no/,""))};e.canPlayOgg=function(){var c=document.createElement("audio");return!(!c.canPlayType||!c.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,""))};e.volumeCanBeSet=function(){var c=document.createElement("audio");if(!c)return!1;c.volume=0;return 0==c.volume?!0:
!1};e.hasPointerEvent=function(){return!!g.navigator.msPointerEnabled};e.isMobile=function(){return e.hasPointerEvent&&1<navigator.msMaxTouchPoints?!0:/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};e.isMac=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("mac")};e.isWin=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("win")};e.isIOS=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)};e.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};
e.isiPad=function(){return-1<navigator.userAgent.indexOf("iPad")};e.isiPhoneIpod=function(){var c=navigator.userAgent;return-1<c.indexOf("iPhone")||-1<c.indexOf("iPod")};e.isSafari=function(){return 0<Object.prototype.toString.call(g.HTMLElement).indexOf("Constructor")};e.isChrome=function(){var c=navigator.userAgent,h=!(0<Object.prototype.toString.call(g.HTMLElement).indexOf("Constructor"))&&"WebkitTransform"in document.documentElement.style;(-1<c.indexOf("iPhone")||-1<c.indexOf("iPod")||-1<c.indexOf("iPad"))&&
c.match("CriOS")&&(h=!0);return h};e.isOpera=function(){return!(!g.opera||!g.opera.version)};e.isIE=function(){var c=g.navigator.userAgent,h=c.indexOf("MSIE ");if(0<h)return parseInt(c.substring(h+5,c.indexOf(".",h)),10);if(0<c.indexOf("Trident/"))return h=c.indexOf("rv:"),parseInt(c.substring(h+3,c.indexOf(".",h)),10);h=c.indexOf("Edge/");return 0<h?parseInt(c.substring(h+5,c.indexOf(".",h)),10):!1};e.parseXML=function(c){if(g.ActiveXObject&&g.GetObject){var h=new ActiveXObject("Microsoft.XMLDOM");
h.loadXML(c);return h}if(g.DOMParser)return(new DOMParser).parseFromString(c,"text/xml");throw Error("No XML parser available");};e.baseUrl=function(){return g.location.href.replace(g.location.hash,"")};e.protocol=function(){return g.location.protocol};e.qualifyURL=function(c){var h=document.createElement("a");h.href=c;return h.href};e.hasLocalStorage=function(){try{return"localStorage"in g&&null!==g.localStorage}catch(c){return!1}};e.validateEmail=function(c){return/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/.test(c)?
!0:!1};e.hasDownloadSupport=function(c){return"download"in document.createElement("a")};e.relativePath=function(c){return/^(?:[a-z]+:)?\/\//i.test(c)};e.getScrollOffsets=function(){if(null!=g.pageXOffset)return{x:g.pageXOffset,y:g.pageYOffset};if("CSS1Compat"==document.compatMode)return{x:document.documentElement.scrollLeft,y:document.documentElement.scrollTop}};e.getViewportSize=function(){return e.hasPointerEvent&&1<navigator.msMaxTouchPoints?{w:document.documentElement.clientWidth||g.innerWidth,
h:document.documentElement.clientHeight||g.innerHeight}:e.isMobile?{w:g.innerWidth,h:g.innerHeight}:{w:document.documentElement.clientWidth||g.innerWidth,h:document.documentElement.clientHeight||g.innerHeight}};e.getViewportMouseCoordinates=function(c){var h=e.getScrollOffsets();return c.touches?{screenX:void 0==c.touches[0]?c.touches.pageX-h.x:c.touches[0].pageX-h.x,screenY:void 0==c.touches[0]?c.touches.pageY-h.y:c.touches[0].pageY-h.y}:{screenX:void 0==c.clientX?c.pageX-h.x:c.clientX,screenY:void 0==
c.clientY?c.pageY-h.y:c.clientY}};e.supportCalc=function(){return checkCalc("-webkit-")||checkCalc("-moz-")||checkCalc()};checkCalc=function(c){c=c||"";var h=document.createElement("div");h.style.cssText=c+"width: calc(1px);";return!!h.style.length};e.supportsTransitions=function(){var c=document.createElement("p").style;return"transition"in c||"WebkitTransition"in c||"MozTransition"in c||"msTransition"in c||"OTransition"in c};e.hasCanvas=function(){return!!document.createElement("canvas")};e.hasFullscreen=
function(){return e.test.requestFullscreen||e.test.mozRequestFullScreen||e.test.msRequestFullscreen||e.test.oRequestFullscreen||e.test.webkitRequestFullScreen};e.preventSelect=function(c){jQuery(c).each(function(){jQuery(this).attr("unselectable","on").css({"-moz-user-select":"none","-webkit-user-select":"none","user-select":"none"}).each(function(){this.onselectstart=function(){return!1}})})};e.disableSelection=function(c){try{c.style.userSelect="none"}catch(h){}try{c.style.MozUserSelect="none"}catch(h){}try{c.style.webkitUserSelect=
"none"}catch(h){}try{c.style.khtmlUserSelect="none"}catch(h){}try{c.style.oUserSelect="none"}catch(h){}try{c.style.msUserSelect="none"}catch(h){}try{c.msUserSelect="none"}catch(h){}c.onselectstart=function(){return!1}};e.counter=function(c){return 9>c?"0"+(c+1):c+1};e.isNumber=function(c){return!isNaN(parseFloat(c))&&isFinite(c)};e.getRandomInt=function(c,h){return Math.floor(Math.random()*(h-c+1))+c};e.formatCurrentTime=function(c){c=Math.round(c);minutes=Math.floor(c/60);minutes=10<=minutes?minutes:
""+minutes;c=Math.floor(c%60);return minutes+":"+(10<=c?c:"0"+c)};e.formatDuration=function(c){c=Math.round(c);minutes=Math.floor(c/60);minutes=10<=minutes?minutes:""+minutes;c=Math.floor(c%60);return minutes+":"+(10<=c?c:"0"+c)};e.hmsToSecondsOnly=function(c){c=c.split(":");for(var h=0,d=1;0<c.length;)h+=d*parseInt(c.pop()),d*=60;return h};e.checkBoolean=function(c){if("string"===typeof c)switch(c.toLowerCase()){case "true":case "yes":case "1":return!0;case "false":case "no":case "0":case null:return!1;
default:return!!c}else if("boolean"===typeof c)return!!c};g.AWPUtils=e})(window);
(function(g,e){g.AWPTooltip=function(c){e("body");e(document);var h=e(g),d=c.parent,m=!1,n;this.setData=function(){n=0<d.find(".awp-tooltip").length?d.find(".awp-tooltip"):e('<div class="awp-tooltip"><p class="awp-tooltip-inner"></p></div>').appendTo(d).hide()};this.show=function(){};this.hide=function(){n.hide()};this.seekbar=function(t,y,p,v){if(m)return!1;n.addClass("awp-tooltip-num").find("p").text(AWPUtils.formatCurrentTime(p)+" / "+AWPUtils.formatDuration(v));p=d.offset().left;v=d.offset().top;
y.offset();var A=y.offset().top;y.outerWidth();var F=y.outerHeight(),E=n.outerWidth(),Q=n.outerHeight(),I=h.width();h.height();var G=h.scrollLeft();h.scrollTop();t=t.pageX;var B=t-p;if(y.hasClass("awp-tooltip-top")){var k=B-E/2;var z=A-v-Q}else y.hasClass("awp-tooltip-bottom")&&(k=B-E/2,z=A-v+F+15);k+E+p-G>I&&(k=t-p-E);0>k+p-G&&(k=t-p);k+E+p-G>I&&(k=I-E-p+G);n.css({left:parseInt(k,10)+"px",top:parseInt(z,10)+"px"}).show()};this.circle=function(t,y,p,v){if(m)return!1;n.addClass("awp-tooltip-num").find("p").text(AWPUtils.formatCurrentTime(p)+
" / "+AWPUtils.formatDuration(v));t=d.offset().left;p=d.offset().top;v=y.offset().left;var A=y.offset().top,F=y.outerWidth();y.outerHeight();var E=n.outerWidth(),Q=n.outerHeight();if(y.hasClass("awp-tooltip-top")){var I=v-t+F/2-E/2;var G=A-p-Q-10}n.css({left:parseInt(I,10)+"px",top:parseInt(G,10)+"px"}).show()};this.volume=function(t,y,p){if(m)return!1;n.addClass("awp-tooltip-num").find("p").text(p+" %");p=d.offset().left;var v=d.offset().top,A=y.offset().left,F=y.offset().top,E=y.outerWidth(),Q=
y.outerHeight(),I=n.outerWidth(),G=n.outerHeight(),B=t.pageX-p;t=t.pageY-v;if(y.hasClass("awp-tooltip-top"))if(y.hasClass("awp-vertical")){var k=A-p+E/2-I/2;var z=t-G-10}else k=B-I/2,z=F-v-G;else y.hasClass("awp-tooltip-bottom")?y.hasClass("awp-vertical")?(k=A-p+E/2-I/2,z=t+G+10):(k=B-I/2,z=F-v+Q+10):y.hasClass("awp-tooltip-left")&&y.hasClass("awp-vertical")&&(k=A-p-I-5,z=t-G/2);n.css({left:parseInt(k,10)+"px",top:parseInt(z,10)+"px"}).show()};this.controls=function(t,y){if(m)return!1;n.removeClass("awp-tooltip-num").find("p").text(y);
var p=d.offset().left,v=d.offset().top,A=t.offset().left,F=t.offset().top,E=t.outerWidth(),Q=t.outerHeight(),I=n.outerWidth(),G=n.outerHeight();t.hasClass("awp-tooltip-top")?(p=A-p+E/2-I/2,v=F-v-G):t.hasClass("awp-tooltip-top-right")?(p=A-p,v=F-v-G):t.hasClass("awp-tooltip-top-left")?(p=A-p+E-I,v=F-v-G):t.hasClass("awp-tooltip-right")?(p=A-p+E+10,v=F-v+Q/2-G/2):t.hasClass("awp-tooltip-bottom")?(p=A-p+E/2-I/2,v=F-v+Q+10):t.hasClass("awp-tooltip-bottom-left")?(p=A-p+E-I,v=F-v+Q+10):t.hasClass("awp-tooltip-left")?
(p=A-p-10-I,v=F-v+Q/2-G/2):(p=A-p+E/2-I/2,v=F-v-G);n.css({left:parseInt(p,10)+"px",top:parseInt(v,10)+"px"}).show()};this.setValue=function(t){n.find("p").text(t)};this.setState=function(t){m=t};this.setData()}})(window,jQuery);
(function(g,e){g.AWPTouchManager=function(c){function h(k){F||e(y).trigger("AWPTouchManager.MOUSE_MOVE",{elem:e(k.currentTarget),e:k})}function d(k){F||(e(k.currentTarget).off("mousemove",h).off("mouseleave",d),p.off("mouseleave",m),e(y).trigger("AWPTouchManager.MOUSE_LEAVE",{elem:e(k.currentTarget),e:k}))}function m(k){e(k.currentTarget).off("mousemove",h).off("mouseleave",d);p.off("mouseleave",m);e(y).trigger("AWPTouchManager.MOUSE_LEAVE",{elem:e(k.currentTarget),e:k})}function n(k){G&&(B=[k.pageX,
k.pageY]);if(!F){var z;if("touchstart"==k.type)if((z=k.originalEvent.touches)&&0<z.length)z=z[0];else return!1;else z=k.originalEvent,k.preventDefault();F=!0;p.on(Q,function(q){a:if(!G||q.pageX!==B[0]||q.pageY!==B[1]){if("touchmove"==q.type){if(q.originalEvent.touches&&q.originalEvent.touches.length)var N=q.originalEvent.touches;else if(q.originalEvent.changedTouches&&q.originalEvent.changedTouches.length)N=q.originalEvent.changedTouches;else break a;if(1<N.length)break a;N=N[0]}else N=q.originalEvent;
q.preventDefault();e(y).trigger("AWPTouchManager.DRAG_MOVE",{elem:A,point:N,e:q})}}).on(I,function(q){t(q)});A.on(I,function(q){t(q)});e(y).trigger("AWPTouchManager.DRAG_START",{elem:A,point:z,e:k})}return!1}function t(k){if(F){F=!1;p.off(Q).off(I);A.off(I);if("touchend"==k.type){if(k.originalEvent.touches&&k.originalEvent.touches.length)var z=k.originalEvent.touches;else if(k.originalEvent.changedTouches&&k.originalEvent.changedTouches.length)z=k.originalEvent.changedTouches;else return!1;if(1<z.length)return!1;
z=z[0]}else z=k.originalEvent;k.preventDefault();v||p.off("mouseleave",m);e(y).trigger("AWPTouchManager.DRAG_RELEASE",{name:"DRAG_RELEASE",elem:A,point:z,e:k})}return!1}var y=this;e("body");var p=e(document);e(g);var v=AWPUtils.isMobile(),A,F=!1,E,Q,I,G=AWPUtils.isChrome(),B=[];this.setData=function(){"ontouchstart"in g?(E="touchstart.ap mousedown.ap",Q="touchmove.ap mousemove.ap",I="touchend.ap mouseup.ap"):g.PointerEvent?(E="pointerdown.ap",Q="pointermove.ap",I="pointerup.ap"):(E="mousedown.ap",
Q="mousemove.ap",I="mouseup.ap");var k,z=c.length;for(k=0;k<z;k++)c[k].on(E,function(q){q.preventDefault();if(F)return!1;A=e(this);n(q);return!1});if(!v)for(k=0;k<z;k++)c[k].on("mouseenter",function(q){if(F)return!1;A=e(this).on("mouseleave",d);if(A.data("apmove"))A.on("mousemove",h);p.on("mouseleave",m);e(y).trigger("AWPTouchManager.MOUSE_ENTER",{elem:A,e:q})})};this.isDrag=function(){return F};this.setData()}})(window,jQuery);
(function(g,e){g.AWPDownloadManager=function(c){function h(Q,I,G){e.ajax({type:"POST",url:t+"includes/mail.php",data:"mail="+Q+"&title="+I+"&path="+G}).done(function(B){v=!1}).fail(function(B,k,z){console.log("Send email error: "+B.responseText);d();v=!1});p.css({marginTop:parseInt(-p.height()/2,10)+"px",display:"block"}).stop().animate({opacity:1},{duration:500});E&&clearTimeout(E);E=setTimeout(d,2E3)}function d(){E&&clearTimeout(E);p.stop().animate({opacity:0},{duration:500,complete:function(){p.css("display",
"none")}})}var m=AWPUtils.isMobile();e("body");e(document);var n=c.parent,t=c.settings.sourcePath,y,p,v,A,F,E;this.setData=function(){y=0<n.find("iframe.awp-dl-iframe").length?n.find("iframe.awp-dl-iframe"):e('<iframe class="awp-dl-iframe"/>').css({position:"absolute",left:"-10000px",display:"none"}).appendTo(n);m&&(p=n.find(".awp-download-confirm"))};this.download=function(Q,I){if(v)return!1;if("file:"==g.location.protocol)return console.log("Downloading files locally is not possible! This requires online server connection."),
!1;var G=Q;var B=I;G.indexOf("\\")&&(G=G.replace(/\\/g,"/"));G.match(/^http([s]?):\/\/.*/)||(G=AWPUtils.qualifyURL(G));m||(B=B.replace(/[^A-Z0-9\-_\.]+/ig,"_"));50<B.length&&(B=B.substr(0,50)+"...");m||/\.(mp3)$/i.test(B)||(B+=".mp3");if(m){v=!0;if(!A){for(var k=prompt("Please enter your email address where download link will be sent:");(!AWPUtils.validateEmail(k)||AWPUtils.isEmpty(k))&&null!=k;)k=prompt("Please enter a valid email address:");(F=k)&&(A=!0)}F?h(F,B,G):v=!1}else y.attr("src",t+"includes/dl.php?path="+
G+"&title="+B)};this.setData()}})(window,jQuery);
(function(g,e){g.AWPShareManager=function(c){AWPUtils.isMobile();var h=c.settings.facebookAppId,d="https:"==g.location.protocol?"https:":"http:";this.setData=function(){if(AWPUtils.isEmpty(h))console.log("facebookAppId has not been set in settings!");else if(!g.FB&&h&&!document.body.querySelector("#fb-root")){var m=document.createElement("script");m.text="window.fbAsyncInit=function(){FB.init({appId:'"+h+"',status:true,xfbml:true})};(function(e,t,n){var r,i=e.getElementsByTagName(t)[0];if(e.getElementById(n)){return}r=e.createElement(t);r.id=n;r.src='"+d+
"//connect.facebook.net/en_US/all.js';i.parentNode.insertBefore(r,i)})(document,'script','facebook-jssdk')";var n=document.createElement("div");n.id="fb-root";document.body.appendChild(n);document.body.appendChild(m)}};this.share=function(m,n,t){var y=(g.screen.width-600)/2,p=(g.screen.height-300)/2,v=n.description||"",A=n.thumb?AWPUtils.qualifyURL(n.thumb):"";n=n.share;AWPUtils.relativePath(A)||(A=AWPUtils.qualifyURL(A));if("facebook"==m){var F=d+"//www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(n);
if(g.FB){g.FB&&FB.ui({method:"feed",name:document.title,link:n,picture:A,caption:t});return}}else"twitter"==m?F=d+"//twitter.com/share?url="+encodeURIComponent(n)+"&text="+encodeURIComponent(t):"tumblr"==m&&(F=d+"//www.tumblr.com/share/link?url="+encodeURIComponent(n)+"&amp;name="+encodeURIComponent(t)+"&amp;description="+encodeURIComponent(v));F&&g.open(F,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=600,height=300,left="+y+",top="+p)};this.setData()}})(window,jQuery);
(function(g,e){g.AWPSoundLoader=function(c){function h(){F.length?(A=F.shift(),Q=0,B=A.limit||500,d()):e(y).trigger("AWPSoundLoader.END_LOAD",[E])}function d(){if("file:"==g.location.protocol)alert("Using "+A.type+" locally is not possible! This requires online server connection!"),h();else{var k=A.type,z=A.path;"podcast"==k?(k=v+"?url="+encodeURIComponent(z),e.ajax({url:k,dataType:"json",cache:!1}).done(function(q){q=q.contents.substr(q.contents.indexOf("<?xml"));var N=AWPUtils.parseXML(q),L,O,oa,
Da=0;e(N).find("image").length&&e(N).find("image").attr("href")?oa=e(N).find("image").attr("href"):e(q).find("itunes\\:image").length&&e(q).find("itunes\\:image").attr("href")&&(oa=e(q).find("itunes\\:image").attr("href"));e(N).find("item").each(function(){if(Da==B)return!1;L=e(this);O=e.extend(!0,{},A);O.type="audio";O.mp3=L.find("enclosure").attr("url");p.createDownloadIconsInPlaylist&&!O.download&&(O.download=O.mp3);!O.title&&L.find("title").length&&(O.title=L.find("title").text());!O.artist&&
L.find("author").length&&(O.artist=L.find("author").text());!O.description&&L.find("description").length&&(O.description=L.find("description").text());!O.duration&&L.find("duration").length&&(O.duration=L.find("duration").text());O.thumb||(L.find("image").length&&L.find("image").attr("href")?O.thumb=L.find("image").attr("href"):oa&&(O.thumb=oa));L.find("link").length&&(O.share||(O.share=L.find("link").text()),!O.link&&p.createLinkIconsInPlaylist&&(O.link=L.find("link").text()));E.push(O);Da++});h()}).fail(function(q,
N,L){console.log(q,N,L);h()})):"soundcloud"==k&&(I?n(z):m(z))}}function m(k){if(AWPUtils.isEmpty(G))return G=p.scak[Math.floor(Math.random()*p.scak.length)],!1;var z=document.createElement("script");z.src="https://connect.soundcloud.com/sdk.js";var q=document.getElementsByTagName("script")[0];q.parentNode.insertBefore(z,q);var N=setInterval(function(){g.SC&&(N&&clearInterval(N),SC.initialize({client_id:G}),I=!0,n(k))},100)}function n(k){SC.get(k,{limit:200,linked_partitioning:1},function(z,q){if(q)console.log("Error getSoundCloudPage: "+
q),h();else{if("track"==z.kind)t(z);else if("playlist"==z.kind){var N,L=z.tracks.length;if(E.length+L>=B){L=B-E.length;var O=!0}for(N=0;N<L;N++)t(z.tracks[N],!0)}else if(z.collection)for(L=z.collection.length,E.length+L>=B&&(L=B-E.length,O=!0),N=0;N<L;N++)t(z.collection[N],!0);z.next_href&&!O?n(z.next_href):h()}})}function t(k,z){if(k.streamable&&k.stream_url){var q=jQuery.extend(!0,{},A);q.deeplink&&"undefined"!==typeof z&&(q.deeplink+=(Q+1).toString(),Q++);q.type="audio";k.duration&&(q.duration=
k.duration);q.mp3=k.stream_url+"?client_id="+G;p.createDownloadIconsInPlaylist&&"undefined"===typeof q.download&&k.downloadable&&k.download_url&&(q.download=q.mp3.replace(/\/stream\\?/,"/download"));!q.title&&k.title&&(q.title=k.title);!q.description&&k.description&&(q.description=k.description);!q.thumb&&k.artwork_url&&(q.thumb=k.artwork_url,q.thumbQuality&&(q.thumb=q.thumb.replace("large.jpg",q.thumbQuality)));q.favoritings_count=parseInt(k.favoritings_count?k.favoritings_count:0,10);q.playback_count=
parseInt(k.playback_count?k.playback_count:0,10);q.hotness=q.favoritings_count+q.playback_count;k.permalink_url&&(q.share||(q.share=k.permalink_url),p.createLinkIconsInPlaylist&&!q.link&&(q.link=k.permalink_url));E.push(q)}}var y=this,p=c.settings,v=p.sourcePath+"includes/ba-simple-proxy.php",A,F=[],E=[],Q,I,G=p.soundCloudAppId;e("<div/>");var B;this.setData=function(k){E=[];F=e.extend(!0,[],[k]);h()}}})(window,jQuery);
(function(g,e){g.AWPPlaylistManager=function(c){function h(){3>d.playlistItems?d.randomPlay=!1:d.randomArr=AWPUtils.randomiseArray(d.playlistItems)}var d=this;this.loopingOn=c.loopingOn;this.randomPlay=c.randomPlay;this.playlistItems;this.lastInOrder=!1;this.counter=-1;this.lastPlayedFromPlaylistClick;this.lastRandomCounter;this.randomPaused=!1;this.randomArr=[];this.playlistSelect=!1;this.setCounter=function(m,n){"undefined"===typeof n&&(n=!0);d.counter=n?d.counter+parseInt(m,10):parseInt(m,10);
if(isNaN(d.counter))alert("AWPPlaylistManager message: No active media, counter = "+d.counter);else if(d.lastInOrder=!1,d.loopingOn){if(d.randomPlay)if(d.counter>d.playlistItems-1){d.counter=d.randomArr[d.playlistItems-1];h();if(d.randomArr[0]==d.counter){var t=d.randomArr.splice(0,1);d.randomArr.push(t)}d.counter=0;e(d).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")}else 0>d.counter&&(d.counter=d.randomArr[0],h(),d.randomArr[d.playlistItems-1]==d.counter&&(t=d.randomArr.splice(d.playlistItems-
1,1),d.randomArr.unshift(t)),d.counter=d.playlistItems-1);else d.counter>d.playlistItems-1?(d.counter=0,e(d).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")):0>d.counter&&(d.counter=d.playlistItems-1);e(d).trigger("AWPPlaylistManager.COUNTER_READY")}else d.counter>d.playlistItems-1?(d.counter=d.playlistItems-1,d.lastInOrder=!0):0>d.counter&&(d.counter=0),d.lastInOrder?e(d).trigger("AWPPlaylistManager.PLAYLIST_END"):e(d).trigger("AWPPlaylistManager.COUNTER_READY")};this.getCounter=function(){return d.randomPlay?
d.playlistSelect?d.counter:d.randomArr[d.counter]:d.counter};this.advanceHandler=function(m){d.playlistSelect=!1;d.randomPaused?(d.randomPaused=!1,d.lastRandomCounter+m>d.playlistItems-1?(d.counter=d.playlistItems-1,e(d).trigger("AWPPlaylistManager.COUNTER_READY")):0>d.lastRandomCounter+m?(d.counter=0,e(d).trigger("AWPPlaylistManager.COUNTER_READY")):d.setCounter(d.lastRandomCounter+m,!1)):d.setCounter(m)};this.processPlaylistRequest=function(m){d.playlistSelect=!1;d.randomPlay&&(d.playlistSelect=
!0,d.lastPlayedFromPlaylistClick=m,d.randomPaused||(d.lastRandomCounter=d.counter,d.randomPaused=!0));this.setCounter(m,!1)};this.setPlaylistItems=function(m,n){"undefined"===typeof n&&(n=!0);n&&(d.counter=-1);d.playlistItems=m;d.randomPlay&&h()};this.reSetCounter=function(m){"undefined"===typeof m?d.counter=-1:(m=parseInt(m,10),d.playlistItems?(m>d.playlistItems-1?m=d.playlistItems-1:0>m&&(m=0),d.counter=m):d.counter=-1)};this.setRandom=function(m){d.randomPlay=m;d.randomPlay&&h();if(d.randomPlay){var n=
d.randomArr.length;for(m=0;m<n;m++)if(d.randomArr[m]==d.counter){if(0==m)break;m=d.randomArr.splice(m,1);d.randomArr.unshift(parseInt(m,10));break}d.counter=0}else d.randomPaused?(d.counter=d.lastPlayedFromPlaylistClick,d.randomPaused=!1):d.counter=d.randomArr[d.counter]};this.setLooping=function(m){d.loopingOn=m}}})(window,jQuery);
(function(g){g.fn.awp=function(e){function c(a){if(!u)return!1;0<M?(eb=M,M=0):M=eb;h();"undefined"!==typeof a&&"undefined"!==typeof ba&&void 0!=Ea.attr("data-awptooltip")&&ba.controls(Ea,0==M?"UnMute":"Mute")}function h(a){"undefined"!==typeof a&&(M=a);"undefined"!==typeof M&&(H.volume=M,"undefined"!==typeof l&&l.setVolume(M));Fa&&(ka?zb.css("width",M*fa+"px"):zb.css("height",M*fa+"px"));0==M?Fa&&Ea.find("i").removeClass("fa-volume-up fa-volume-down").addClass("fa-volume-off"):Fa&&Ea.find("i").removeClass("fa-volume-off fa-volume-down").addClass("fa-volume-up");
"undefined"!==typeof awpVolumeChange&&awpVolumeChange(J,R,M)}function d(a){a.preventDefault();if(!u)return!1;var b=g(a.currentTarget),f=b.attr("data-id");if(f==w.getCounter())return!1;fb=!0;w.processPlaylistRequest(f);"undefined"!==typeof awpPlaylistItemClick&&awpPlaylistItemClick(J,R,b,f,a)}function m(a){a.preventDefault();if(!u)return!1;a=g(a.currentTarget);var b=a.attr("data-id");if(b==w.getCounter())return!1;a.removeClass("awp-playlist-non-selected").addClass("awp-playlist-selected");"undefined"!==
typeof awpPlaylistItemRollover&&awpPlaylistItemRollover(J,R,a,b)}function n(a){a.preventDefault();if(!u)return!1;a=g(a.currentTarget);var b=a.attr("data-id");if(b==w.getCounter())return!1;a.removeClass("awp-playlist-selected").addClass("awp-playlist-non-selected");"undefined"!==typeof awpPlaylistItemRollout&&awpPlaylistItemRollout(J,R,a,b)}function t(a){if(!u)return!1;a=g(a.currentTarget);a.hasClass("awp-prev-toggle")?J.previousMedia():a.hasClass("awp-playback-toggle")?J.togglePlayback():a.hasClass("awp-next-toggle")?
J.nextMedia():a.hasClass("awp-loop-toggle")?(ca=!ca,w.setLooping(ca),ca?va.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):va.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")):a.hasClass("awp-player-volume")?a.hasClass("awp-toggle-mute")&&c():a.hasClass("awp-random-toggle")?(da=!da,w.setRandom(da),da?wa.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):wa.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")):
a.hasClass("awp-sort-alpha")?(J.sort("title",Pa),(Pa=!Pa)?a.find("i").removeClass("fa-sort-alpha-desc").addClass("fa-sort-alpha-asc"):a.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc")):a.hasClass("awp-share-item")&&void 0!=a.attr("data-type")&&"undefined"!==typeof Ab&&C.share&&!AWPUtils.isEmpty(C.share)&&Ab.share(a.attr("data-type").toLowerCase(),C,Ga(w.getCounter()))}function y(a){if(!u)return!1;a.preventDefault();if("undefined"!==typeof gb&&gb.isDrag())return!1;a=g(a.currentTarget);
var b=a.find("i");b.hasClass("awp-icon-color")&&b.removeClass("awp-icon-color").addClass("awp-icon-rollover-color");"undefined"!==typeof ba&&void 0!=a.attr("data-awptooltip")&&(b=a.hasClass("awp-player-volume")?0==M?"UnMute":"Mute":a.attr("data-awptooltip"),ba.controls(a,b))}function p(a){if(!u)return!1;a.preventDefault();a=g(a.currentTarget);var b=a.find("i");a.hasClass("awp-random-toggle")&&da||a.hasClass("awp-loop-toggle")&&ca||b.hasClass("awp-icon-rollover-color")&&b.removeClass("awp-icon-rollover-color").addClass("awp-icon-color");
"undefined"!==typeof ba&&ba.hide()}function v(){if(-1!=w.getCounter()){var a=ja,b=U.children("div.awp-playlist-item[data-id="+a+"]"),f=b.find(".awp-playlist-non-selected, .awp-playlist-selected");b.length&&(a=b.attr("data-id"),f.removeClass("awp-playlist-selected").addClass("awp-playlist-non-selected"),"undefined"!==typeof awpPlaylistItemEnabled&&awpPlaylistItemEnabled(J,R,b,a))}}function A(a){Qa=g.ajax({url:Ha+"peaks/peaks.php",type:"post",data:[{name:"action",value:"awp_read_peaks"},{name:"id",
value:a},{name:"path",value:C.peakdir||null}],dataType:"json"}).done(function(b){b.length?(l.backend.peaks=b,Ra=!0,hb?l.drawBuffer():l.load(Z,l.backend.peaks)):(l.backend.supportsWebAudio()?(ib=!0,C.remote&&(Ia.css("opacity",1).html("Loading waveform..."),l.setSkipArrayBuffer(!0),Q())):C.peakImage&&(pa=!0,jb.empty().append('<img src="'+C.peakImage.load+'" alt="load"/>'),xa.empty().append('<img src="'+C.peakImage.progress+'" alt="progress"/>'),ea.css("display","block"),xa.width(ea.width()),ea.removeClass("awp-hidden").addClass("awp-visible"),
Sa()),l.load(Z))}).fail(function(b,f,r){console.log(b,f,r)})}function F(a,b){g.ajax({url:Ha+"peaks/peaks.php",type:"post",data:[{name:"action",value:"awp_write_peaks"},{name:"peaks",value:a},{name:"id",value:b},{name:"path",value:C.peakdir||null}],dataType:"json"}).done(function(f){}).fail(function(f,r,x){console.log(f.responseText)})}function E(){if(Tb&&C.wav)Z=C.wav;else if(Ub&&C.aac)Z=C.aac;else if(Vb&&C.mp3)Z=C.mp3;else{alert("No required audio format supplied! Please add mp3 audio format to play!");
return}-1!=Z.indexOf("ebsfm:")&&(Z=atob(Z.substr(6)));C.peakData?(l.backend.peaks=C.peakData,Ra=!0,hb?l.drawBuffer():l.load(Z,l.backend.peaks)):C.peakImage?(pa=!0,jb.empty().append('<img src="'+C.peakImage.load+'" alt="load"/>'),xa.empty().append('<img src="'+C.peakImage.progress+'" alt="progress"/>'),ea.css("display","block"),xa.width(ea.width()),ea.removeClass("awp-hidden").addClass("awp-visible"),Sa(),l.setSkipArrayBuffer(!0),l.load(Z)):A(C.peakName||C.title)}function Q(){Ta=g.ajax({url:Ha+"peaks/remote_dl.php",
type:"post",data:[{name:"id",value:Z},{name:"title",value:C.title},{name:"path",value:C.peakdir||null}],dataType:"json"}).done(function(a){console.log(a);l._getArrayBuffer(a)}).fail(function(a,b,f){console.log(a,b,f)})}function I(a){ha=!0;Bb();aa&&kb();var b=Wb.find("#"+a);if(0==b.length)return alert('Failed to select playlist! Check activePlaylist option in settings. Make sure that element: "'+a+'" exist in awp-playlist-list!'),lb.css("display","none"),ha=!1;"undefined"!==typeof awpPlaylistStartLoad&&
awpPlaylistStartLoad(J,R);var f,r;b.find(".awp-playlist-item").each(function(){r=g(this);f=G(r);la.push(f)});P=la.length;B()}function G(a){var b={};b.origclasses=a.attr("class");b.type=b.origtype=a.attr("data-type");a.is(":empty")||(b.content=a.html());void 0!=a.attr("data-mp3")&&(b.mp3=a.attr("data-mp3"));void 0!=a.attr("data-wav")&&(b.wav=a.attr("data-wav"));void 0!=a.attr("data-aac")&&(b.aac=a.attr("data-aac"));void 0==a.attr("data-path")||AWPUtils.isEmpty(a.attr("data-path"))||(b.path=a.attr("data-path"),
-1!=b.path.indexOf("ebsfm:")&&(b.path=atob(b.path.substr(6))));void 0==a.attr("data-peak-load")||AWPUtils.isEmpty(a.attr("data-peak-load"))||void 0==a.attr("data-peak-progress")||AWPUtils.isEmpty(a.attr("data-peak-progress"))||(b.peakImage={load:a.attr("data-peak-load"),progress:a.attr("data-peak-progress")});void 0!=a.attr("data-peak-array")&&(b.peakData=a.attr("data-peak-array").split(","));void 0!=a.attr("data-peak-name")&&(b.peakName=a.attr("data-peak-name"));AWPUtils.isEmpty(a.html())||(b.content=
a.html());void 0!=a.attr("data-limit")&&!AWPUtils.isEmpty(a.attr("data-limit"))&&AWPUtils.isNumber(a.attr("data-limit"))&&0!=Math.abs(parseInt(a.attr("data-limit"),10))&&(b.limit=Math.abs(parseInt(a.attr("data-limit"),10)));void 0==a.attr("data-thumb")||AWPUtils.isEmpty(a.attr("data-thumb"))?void 0==a.attr("data-thumb-default")||AWPUtils.isEmpty(a.attr("data-thumb-default"))||(b.thumbDefault=a.attr("data-thumb-default")):b.thumb=a.attr("data-thumb");void 0==a.attr("data-thumb-quality")||AWPUtils.isEmpty(a.attr("data-thumb-quality"))||
(b.thumbQuality=a.attr("data-thumb-quality"));void 0==a.attr("data-title")||AWPUtils.isEmpty(a.attr("data-title"))||(b.title=a.attr("data-title"));void 0==a.attr("data-artist")||AWPUtils.isEmpty(a.attr("data-artist"))||(b.artist=a.attr("data-artist"));void 0==a.attr("data-description")||AWPUtils.isEmpty(a.attr("data-description"))||(b.description=a.attr("data-description"));void 0!=a.attr("data-download")&&(b.download=a.attr("data-download"));void 0!=a.attr("data-id3")&&(b.id3=!0);void 0==a.attr("data-dir-url")||
AWPUtils.isEmpty(a.attr("data-dir-url"))||(b.dirurl=a.attr("data-dir-url"));void 0==a.attr("data-peak-dir")||AWPUtils.isEmpty(a.attr("data-peak-dir"))||(b.peakdir=a.attr("data-peak-dir"));void 0!=a.attr("data-start")&&!AWPUtils.isEmpty(a.attr("data-start"))&&AWPUtils.isNumber(a.attr("data-start"))&&0!=a.attr("data-start")&&(b.start=Math.abs(a.attr("data-start")));void 0!=a.attr("data-end")&&!AWPUtils.isEmpty(a.attr("data-end"))&&AWPUtils.isNumber(a.attr("data-end"))&&0!=a.attr("data-end")&&(b.end=
Math.abs(a.attr("data-end")));void 0!=a.attr("data-duration")&&!AWPUtils.isEmpty(a.attr("data-duration"))&&AWPUtils.isNumber(a.attr("data-duration"))&&0!=Math.abs(a.attr("data-duration"))&&(b.duration=Math.abs(a.attr("data-duration")));void 0!=a.attr("data-playback-rate")&&(b.playbackRate=1,!AWPUtils.isEmpty(a.attr("data-playback-rate"))&&AWPUtils.isNumber(a.attr("data-playback-rate"))&&0!=a.attr("data-playback-rate")&&(b.playbackRate=Math.abs(a.attr("data-playback-rate"))));void 0==a.attr("data-link")||
AWPUtils.isEmpty(a.attr("data-link"))||(b.link=a.attr("data-link"),b.target="_blank",void 0==a.attr("data-target")||AWPUtils.isEmpty(a.attr("data-target"))||(b.target=a.attr("data-target")));void 0!=a.attr("data-share")&&(b.share=a.attr("data-share"));void 0!=a.attr("data-remote")&&(b.remote=!0);void 0==a.attr("data-sort")||AWPUtils.isEmpty(a.attr("data-sort"))||(b.sort=a.attr("data-sort"));return b}function B(){ya++;if(ya>P-1)N();else{var a=la[ya],b=la[ya].type;/^audio$/.test(b)?(ia.push(a),B()):
-1<g.inArray(b,Xb)?Cb.setData(a):/^folder$/.test(b)?k(a):/^gdrive-folder$/.test(b)?z(a):(console.log("Wrong data-type in playlist! Type = "+b),B())}}function k(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),B(),!1;var b=a.path.replace(/\/\//g,"/"),f=Ha+"includes/folder_parser.php";b={dir:b,limit:a.limit||1E4};a.id3&&(mb=qa=ia.length-1);g.ajax({type:"GET",url:f,data:b,dataType:"json"}).done(function(r){a.sort&&
("filename-asc"==a.sort?AWPUtils.keysrt(r,"filename"):"filename-desc"==a.sort?AWPUtils.keysrt(r,"filename",!0):"date-asc"==a.sort?AWPUtils.keysrt(r,"filemtime"):"date-desc"==a.sort&&AWPUtils.keysrt(r,"filemtime",!0));var x,D=r.length;for(x=0;x<D;x++){var S=r[x];var T=g.extend(!0,{},a);T.type="audio";var ra=T.dirurl?T.dirurl+S.basename:S.fullpath;T[S.extension]=ra;T.title||(T.title=S.filename);Db&&!T.download&&(T.download=ra);T.share||(T.share=ra);Eb&&!T.link&&(T.link=ra);ia.push(T);qa++}a.id3?q():
B()}).fail(function(r,x,D){console.log("Error processing folder: "+r.responseText);B()})}function z(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),B(),!1;if(AWPUtils.isEmpty(H.gDriveAppId))return console.log("gDriveAppId has not been set in settings!"),B(),!1;g.ajax({url:"https://www.googleapis.com/drive/v3/files?q='"+a.path+"'+in+parents&pageSize=1000&key="+H.gDriveAppId,dataType:"jsonp"}).done(function(b){var f,
r=b.files.length,x=[],D=[];for(f=0;f<r;f++){var S=b.files[f];/mp3|mpeg|mpeg3|wav|aac|adts/.test(S.mimeType)?(D.push(S),AWPUtils.keysrt(D,"name")):/jpg|jpeg|png/.test(S.mimeType)&&(x.push(S),AWPUtils.keysrt(x,"name"))}a.sort&&("filename-asc"==a.sort?(AWPUtils.keysrt(D,"name"),AWPUtils.keysrt(x,"name")):"filename-desc"==a.sort&&(AWPUtils.keysrt(D,"name",!0),AWPUtils.keysrt(x,"name",!0)));r=D.length;for(f=0;f<r;f++){S=D[f];b=g.extend(!0,{},a);b.type="audio";var T=S.name.substr(S.name.lastIndexOf(".")+
1);b[T.toLowerCase()]="https://drive.google.com/uc?export=download&id="+S.id;x.length&&!b.thumb&&x[f]&&(b.thumb="https://drive.google.com/uc?export=view&id="+x[f].id);b.title||(b.title=S.name.substr(0,S.name.lastIndexOf(".")));Db&&!b.download&&(b.download="https://drive.google.com/uc?export=download&id="+S.id);b.share||(b.share="https://drive.google.com/open?id="+S.id);Eb&&!b.link&&(b.link="https://drive.google.com/open?id="+S.id);ia.push(b)}B()}).fail(function(b,f,r){console.log("Error processing gdrive folder: "+
b.responseText);B()})}function q(){var a=ia[qa];jsmediatags.read(a.mp3||a.wav||a.aac,{onSuccess:function(b){var f=b.tags;b=f.picture;f.artist&&(a.artist=f.artist);f.title&&(a.title=f.title);f.album&&(a.album=f.album);if(b){f="";var r,x=b.data.length;for(r=0;r<x;r++)f+=String.fromCharCode(b.data[r]);a.thumb="data:"+b.format+";base64,"+window.btoa(f)}qa--;qa>mb?q():B()},onError:function(b){console.log("ID3 error: ",b.type,b.info);qa--;qa>mb?q():B()}})}function N(){var a,b=ma?X:V.length,f=ia.length,
r=0;for(a=0;a<f;a++){var x=a+b;ma&&r++;var D=ia[a];var S=D.type;if(sa){D.origclasses||(D.origclasses="awp-playlist-item");var T=g('<div class="'+D.origclasses+'"/>').attr({"data-type":S});delete D.origclasses;if(ma){ra?ra.after(T):za?T.appendTo(U):U.children("div").eq(X).before(T);var ra=T}else T.appendTo(U);var Ja=g('<a class="awp-playlist-non-selected" href="#"/>').on("click",d).appendTo(T);if(!Ka)Ja.on("mouseenter",m).on("mouseleave",n);if(-1!=g.inArray("thumb",Fb)){var Aa=D.thumb||D.thumbDefault;
if(Aa){var Ua=new Image;Ua.className="awp-hidden";Ua.onload=function(){this.className="awp-visible"};Ua.src=Aa;g('<span class="awp-playlist-thumb"></span>').append(Ua).appendTo(Ja)}}-1!=g.inArray("title",Fb)&&g('<span class="awp-playlist-title"></span>').appendTo(Ja);D.link&&(Aa=g('<a class="awp-link" href="'+D.link+'" target="'+(D.target||"_blank")+'"><i class="fa fa-external-link"></i></a>'),Ja.after(Aa));D.download&&(Aa=Gb?g('<a class="awp-download" href="'+D.download+'" download title="Download"><i class="fa fa-download"></i></a>'):
g('<a class="awp-download" href="#" title="Download"><i class="fa fa-download"></i></a>'),Ja.after(Aa));D.content&&(T.after(D.content),delete D.content)}V.splice(x,0,{id:x,type:S,data:D})}sa&&O();aa=U;L();console.log("playlistDataArr = ",V);ma||nb?(x=w.getCounter(),w.setPlaylistItems(P,!1),X<=x&&(za||w.reSetCounter(x+r)),La?(La=!1,Ma&&!Ka&&(ta=!0),w.setCounter(X,!1)):Ma&&w.setCounter(X,!1),-1!=w.getCounter()&&(ja=w.getCounter())):w.setPlaylistItems(P);Da();0==P&&"undefined"!==typeof awpPlaylistEmpty&&
awpPlaylistEmpty(J,R,U);Va=!0;"undefined"!==typeof awpPlaylistEndLoad&&awpPlaylistEndLoad(J,R,U)}function L(){P=V.length;if(sa){var a=0,b,f,r,x;Wa=[];U.find("div.awp-playlist-item").each(function(){f=g(this).attr("data-id",a);r=f.find(".awp-playlist-non-selected, .awp-playlist-selected").attr("data-id",a);x=r.find(".awp-playlist-title");x.length&&(b=Ga(a),ob&&(Wa.push(b.toLowerCase()),V[a].data.title_full=b),Hb?x.html(AWPUtils.counter(a)+Ib+b):x.html(b));V[a].id=a;a++});Xa&&Ya&&0<P&&"h"==Za.charAt(0)&&
ua.mCustomScrollbar("update")}}function O(){U.children(".awp-playlist-item").each(function(){if(!Gb)g(this).find("a[class=awp-download]").off("click").on("click",function(a){a.preventDefault();"undefined"!==typeof Jb&&(a=g(this).parent().attr("data-id"),a=V[a].data,"undefined"===typeof a.download||AWPUtils.isEmpty(a.download)||Jb.download(a.download,a.title||"media"))})})}function oa(a){var b="h"==Za.charAt(0)?"x":"y";ua.mCustomScrollbar({axis:b,theme:a||H.playlistScrollTheme,scrollInertia:0,mouseWheel:{normalizeDelta:!0,
deltaFactor:50,preventDefault:!0},keyboard:{enable:!1},advanced:{autoExpandHorizontalScroll:!0}});Ya=!0}function Da(){ma=nb=!1;lb.css("display","none");ha=!1;u||(u=!0,sa&&!Ya&&Xa&&oa(),h(M),awpSetupDone(J,R));if(!pb&&!ma&&0<P){var a=H.activeItem;a>P-1&&(a=P-1);-1<a&&w.setCounter(a,!1);pb=!0}}function Kb(){"undefined"!==typeof awpMediaEnd&&awpMediaEnd(J,R,w.getCounter());if(Yb)J.nextMedia();else{var a=C.start||0;"loop"==qb?l.play(a):"rewind"==qb?(l.pause(),l.seekTo(a/l.getDuration())):"stop"==qb&&
l.pause()}}function Lb(){u&&"undefined"!==typeof W&&(sa&&-1!=ja&&v(),$a(),w.reSetCounter())}function $a(){Ta&&(Ta.abort(),Ta=null);Qa&&(Qa.abort(),Qa=null);"undefined"!==typeof l&&(l.empty(),l.setSkipArrayBuffer(!1));Ia.css("opacity",0);ab.removeClass("awp-visible").addClass("awp-hidden");pa=!1;jb.empty();xa.empty();ea.css("display","none").removeClass("awp-visible").addClass("awp-hidden");Na.removeClass("awp-visible").addClass("awp-hidden");Oa.removeClass("awp-visible").addClass("awp-hidden");Mb&&
(Na.html("0:00"),Oa.html("0:00"));bb.empty();rb();W=null;Ma=cb=Y=!1;"undefined"!==typeof awpCleanMedia&&awpCleanMedia(J,R)}function kb(){W&&$a();sa&&aa.find(".awp-playlist-item").remove();Ba=aa=null;Va=La=ma=!1;ja=-1;pb=!1;P=0;ya=-1;V=[];ia=[];la=[];w.reSetCounter();ob&&Nb.val(sb);Zb&&(Pa=!1,tb.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc"));"undefined"!==typeof awpDestroyPlaylist&&awpDestroyPlaylist(J,R,U)}function Sa(){Na.removeClass("awp-hidden").addClass("awp-visible");
Oa.removeClass("awp-hidden").addClass("awp-visible")}function rb(){ub.find("i").removeClass("fa-pause").addClass("fa-play")}function Bb(){lb.css("display","block")}function vb(a){if("string"===typeof a)var b=a;else"number"===typeof a&&(b=Ga(a),Hb&&(b=AWPUtils.counter(a)+Ib+b));$b.html(b)}function Ga(a){a=V[a].data;var b="";"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||
AWPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(b=a.artist):b=a.title:b=a.artist+Ob+a.title;return b}var H=g.extend({},{instanceName:"",sourcePath:"",playlistList:"",activePlaylist:"",activeItem:0,volume:.5,autoPlay:!1,randomPlay:!1,loopingOn:!0,autoAdvanceToNextMedia:!0,mediaEndAction:"loop",soundCloudAppId:"",seekTime:10,usePlaylistScroll:!1,playlistScrollOrientation:"vertical",playlistScrollTheme:"light",useKeyboardNavigationForPlayback:!1,
facebookAppId:"",scak:"4e6c7139ca2791a89863367ba374a28e r4wruADPCq7iqJomagvYpdehvILa2bgE b972bf0e059078490e8579b43bf95923 64c56d14d1844681f7cca8c61ec0082a 86b6a66bb2d863f5d64dd8a91cd8de94 8da368dc752f739dcf6e4abb8317548d b4bee2a55625cf4ab8e3f7ea1d35e103 0aff03b3b79c2ac02fd2283b300735bd".split(" "),useNumbersInPlaylist:!1,numberTitleSeparator:".  ",artistTitleSeparator:" - ",playlistItemContent:"title",createDownloadIconsInPlaylist:!1,createLinkIconsInPlaylist:!1,togglePlaybackOnMultipleInstances:!1},
e),K=g(this).show(),Wb=g(H.playlistList).hide(),ac=K.find(".awp-playlist-holder"),ua=K.find(".awp-playlist-inner"),U=K.find(".awp-playlist-content"),wb=K.find(".awp-playlist-filter-msg"),tb=K.find(".awp-sort-alpha"),lb=K.find(".awp-preloader");K.find(".awp-player-holder");var bb=K.find(".awp-player-thumb"),Na=K.find(".awp-media-time-current"),Oa=K.find(".awp-media-time-total"),$b=K.find(".awp-media-title");K.find(".awp-player-controls");var ub=K.find(".awp-playback-toggle"),va=K.find(".awp-loop-toggle"),
Ea=K.find(".awp-player-volume"),wa=K.find(".awp-random-toggle");K.find(".awp-volume-wrapper");var Ca=K.find(".awp-volume-seekbar"),na=K.find(".awp-volume-bg"),zb=K.find(".awp-volume-level"),ab=K.find(".awp-waveform"),Ia=K.find(".awp-waveform-preloader"),ea=K.find(".awp-waveform-img"),jb=K.find(".awp-waveform-img-load"),Pb=K.find(".awp-waveform-img-progress-wrap"),xa=K.find(".awp-waveform-img-progress"),Ka=AWPUtils.isMobile(),Vb=AWPUtils.canPlayMp3(),Tb=AWPUtils.canPlayWav(),Ub=AWPUtils.canPlayAac(),
Ha=H.sourcePath,R=AWPUtils.filterAllowedChars(H.instanceName),Ba=H.activePlaylist,ta=H.autoPlay,hb=H.drawWaveWithoutLoad,ca=H.loopingOn,da=H.randomPlay,Hb=H.useNumbersInPlaylist,Ib=H.numberTitleSeparator,Ob=H.artistTitleSeparator,M=H.volume,Xa=H.usePlaylistScroll,Za=H.playlistScrollOrientation.toLowerCase(),bc=H.useKeyboardNavigationForPlayback,Yb=H.autoAdvanceToNextMedia,qb=H.mediaEndAction,Fb=H.playlistItemContent.split(","),Db=H.createDownloadIconsInPlaylist,Eb=H.createLinkIconsInPlaylist,sa=ac.length,
ob=K.find(".awp-search-filter").length,Zb=tb.length,Mb=Na.length||Oa.length,Fa=Ca.length,u=!1,ha=!1,J=this;g("body");var cc=g(window),dc=g(document),Qb=AWPUtils.isIE();AWPUtils.isChrome();AWPUtils.isSafari();var xb,Gb=AWPUtils.hasDownloadSupport(),ib,pa,Ra,Ta,Qa,za,X,ma,Ma,La,nb,ya=-1,V=[],ia=[],la=[],P=0,pb,Va=!1,aa=null,ja=-1,cb=!1,W,Z,Y=!1,C,fb,Ya,Pa=!1,Wa=[],qa,mb,Xb=["podcast","soundcloud","soundcloud_query"];"undefined"===typeof window.awp_mediaArr&&(window.awp_mediaArr=[]);awp_mediaArr.push({inst:J,
id:R});Ka&&(ta=!1);if(Qb&&12>Qb)ea.on("click",function(a){if(pa){var b=g(a.currentTarget);a=Math.min(Math.max((a.pageX-b.offset().left)/b.width(),0),1);l.seekTo(a)}});ca&&va.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color");da&&wa.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color");if(ob)var Nb=K.find(".awp-search-filter").on("focus",function(a){g(this).val()==sb&&g(this).val("")}).on("blur",function(){AWPUtils.isEmpty(g(this).val())&&g(this).val(sb)}).on("keyup.apfilter",
function(){if(0==Wa.length)return!1;var a=V.length,b=g(this).val();b=Wa.filter(/./.test.bind(new RegExp(b,"i")));var f,r=0;for(f=0;f<a;f++){var x=Ga(f).toLowerCase();-1<g.inArray(x,b)?U.children("div.awp-playlist-item").eq(f).show():(U.children("div.awp-playlist-item").eq(f).hide(),r++)}0<a&&wb.length&&(r==a?wb.show():wb.hide());Xa&&0<P&&"h"==Za.charAt(0)&&ua.mCustomScrollbar("update");"undefined"!==typeof awpFilterChange&&awpFilterChange(J,R,U)}),sb=Nb.val();var ba=new AWPTooltip({settings:H,parent:K}),
Jb=new AWPDownloadManager({settings:H,parent:K}),Ab=new AWPShareManager({settings:H}),w=new AWPPlaylistManager({randomPlay:da,loopingOn:ca});g(w).on("AWPPlaylistManager.COUNTER_READY",function(){W&&$a();if(sa){-1!=ja&&v();var a=w.getCounter(),b=U.children("div.awp-playlist-item[data-id="+a+"]"),f=b.find(".awp-playlist-non-selected, .awp-playlist-selected");b.length&&(ja=a,f.removeClass("awp-playlist-non-selected").addClass("awp-playlist-selected"),Xa&&0<P&&(fb||("h"==Za.charAt(0)?ua.mCustomScrollbar("scrollTo",
parseInt(b.position().left),{scrollInertia:500}):ua.mCustomScrollbar("scrollTo",parseInt(b.position().top),{scrollInertia:500})),fb=!1),"undefined"!==typeof awpPlaylistItemDisabled&&awpPlaylistItemDisabled(J,R,b,a))}a=w.getCounter();C=V[a].data;W=C.type;vb(a);E();"undefined"!==typeof awpItemTriggered&&awpItemTriggered(J,R,a)}).on("AWPPlaylistManager.PLAYLIST_END AWPPlaylistManager.PLAYLIST_END_ALERT",function(){"undefined"!==typeof awpPlaylistEnd&&awpPlaylistEnd(J,R)});var Cb=new AWPSoundLoader({settings:H,
sourcePath:Ha});g(Cb).on("AWPSoundLoader.END_LOAD",function(a,b){var f,r=b.length;for(f=0;f<r;f++){var x=b[f];ia.push(x)}B()});var yb=[];Fa&&(Ca.data("apmove",!0),yb.push(Ca));if(yb.length){var gb=new AWPTouchManager(yb);g(gb).on("AWPTouchManager.DRAG_START",function(a,b){}).on("AWPTouchManager.DRAG_MOVE AWPTouchManager.DRAG_RELEASE",function(a,b){if(!u)return!1;var f=b.elem,r=b.point.pageX,x=b.point.pageY;if(f.hasClass("awp-volume-seekbar")){var D=ka?r:x;ka?M=Math.max(0,Math.min(1,(D-na.offset().left)/
fa)):(M=Math.max(0,Math.min(1,(D-na.offset().top)/fa)),M=1-M);h();"undefined"!==typeof ba&&f.is('[class*="awp-tooltip"]')&&(f=ka?r-na.offset().left:x-na.offset().top,0>f?f=0:f>fa&&(f=fa),f=Math.max(0,Math.min(1,f/fa)),ka||(f=1-f),f=parseInt(100*f,10),ba.volume(b.point,Ca,f))}}).on("AWPTouchManager.MOUSE_MOVE",function(a,b){if(!u)return!1;var f=b.elem;a=b.e;var r=a.pageX,x=a.pageY;f.hasClass("awp-volume-seekbar")&&"undefined"!==typeof ba&&f.is('[class*="awp-tooltip"]')&&(f=ka?r-na.offset().left:x-
na.offset().top,0>f?f=0:f>fa&&(f=fa),f=Math.max(0,Math.min(1,f/fa)),ka||(f=1-f),f=parseInt(100*f,10),ba.volume(a,Ca,f))}).on("AWPTouchManager.MOUSE_LEAVE",function(a,b){if(!u)return!1;"undefined"!==typeof ba&&ba.hide()})}if(Fa){var ka=Ca.hasClass("awp-vertical")?!1:!0,eb=.5,fa=void 0!=H.volumeSize?H.volumeSize:ka?na.width():na.height();0>M?M=0:1<M&&(M=1);0!=M&&(eb=M)}if(bc)dc.on("keyup.apnav",function(a){if(!u)return!1;var b=a.keyCode;g(a.target);37==b?J.previousMedia():39==b?J.nextMedia():32==b?
J.togglePlayback():77==b&&c()});var Rb=[K.find(".awp-next-toggle"),K.find(".awp-prev-toggle"),K.find(".awp-playlist-toggle"),K.find(".awp-share-item"),tb,Ea,ub,va,wa],ec=Rb.length,db;for(db=0;db<ec;db++){var fc=g(Rb[db]).css("cursor","pointer").on("click",t);if(!Ka)fc.on("mouseenter",y).on("mouseleave",p)}window.AudioContext=window.AudioContext||window.webkitAudioContext;var Sb=new AudioContext;"suspended"===Sb.state&&(rb(),Y=!1,"undefined"!==typeof awpAutoplayFail&&awpAutoplayFail(J,R,w.getCounter()));
var l=Object.create(WaveSurfer);l.init({container:ab[0],backend:"MediaElement",audioContext:Sb,interact:1,hideScrollbar:!0,waveColor:H.wavesurfer.waveColor,progressColor:H.wavesurfer.progressColor,barWidth:H.wavesurfer.barWidth,cursorColor:H.wavesurfer.cursorColor,cursorWidth:H.wavesurfer.cursorWidth,height:H.wavesurfer.height});l.on("loading",function(a){a="Loading... "+a.toString()+"%";Ia.css("opacity",1).html(a)});l.on("finish",function(a){Kb()});l.on("error",function(a){console.log(a);"undefined"!==
typeof awpMediaError&&awpMediaError(J,R,w.getCounter())});l.on("audioprocess",function(a){a=l.getCurrentTime();var b=l.getDuration();Mb&&(Na.html(AWPUtils.formatCurrentTime(a)),Oa.html(AWPUtils.formatDuration(b)));pa&&Pb.width(ea.width()*l.backend.getPlayedPercents());C.end&&a>=C.end&&Kb()});l.on("play",function(){console.log("play");cb||("undefined"!==typeof awpMediaStart&&awpMediaStart(J,R,w.getCounter()),cb=!0);ub.find("i").removeClass("fa-play").addClass("fa-pause");Y=!0;"undefined"!==typeof awpMediaPlay&&
awpMediaPlay(J,R,w.getCounter())});l.on("pause",function(){l.isPlaying()||(rb(),Y=!1,"undefined"!==typeof awpMediaPause&&awpMediaPause(J,R,w.getCounter()))});l.on("seek",function(a){pa&&Pb.width(ea.width()*a)});l.on("ready",function(){console.log("ready");l.setVolume(M);var a=C.start||0;if(C.end)var b=C.end;C.playbackRate&&l.setPlaybackRate(C.playbackRate);ta&&(b?l.play(a,b):l.play(a));ta=!0});l.on("waveform_ME_noPeaks",function(){if(ib){var a=l.backend.getPeaks(900);a.length&&F(a,C.peakName||C.title);
ib=!1}Ia.css("opacity",0);ab.removeClass("awp-hidden").addClass("awp-visible");Sa()});l.on("redraw",function(){Ra&&(Ia.css("opacity",0),ab.removeClass("awp-hidden").addClass("awp-visible"),Sa(),Ra=!1)});this.getTitleFormatted=function(a,b){var f="",r=b||Ob;"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||
"undefined"!==typeof a.title||(f=a.artist):f=a.title:f=a.artist+r+a.title;return f};cc.resize(function(){if(!u)return!1;xb&&clearTimeout(xb);xb=setTimeout(J.resize,150);pa&&xa.width(ea.width())});J.resize=function(){l&&(l.drawer.containerWidth=l.drawer.container.clientWidth,l.drawBuffer(),Y||l.drawer.updateProgress(l.backend.getPlayedPercents()))};this.loadPlayMedia=function(){if(!u||!W||!C)return!1;Z&&l.backend.peaks&&l.load(Z,l.backend.peaks,!0);Y=!0};this.playMedia=function(){if(!u||!W||Y)return!1;
"undefined"!==typeof l&&l.play();Y=!0};this.pauseMedia=function(){if(!u||!W||!Y)return!1;"undefined"!==typeof l&&l.pause();Y=!1};this.checkMedia=function(a){if(!u||!W)return!1;a=a.toLowerCase();Y&&"pause"==a&&("undefined"!==typeof l&&l.pause(),Y=!1)};this.togglePlayback=function(){if(!u||!W)return!1;"undefined"!==typeof l&&(!cb&&hb&&l.backend.peaks?(ta=!0,J.loadPlayMedia()):l.playPause())};this.stop=function(){if(!u||!W)return!1;"undefined"!==typeof l&&l.stop();Y=!1};this.nextMedia=function(){if(!u||
!aa)return!1;w.advanceHandler(1,!0)};this.previousMedia=function(){if(!u||!aa)return!1;w.advanceHandler(-1,!0)};this.loadMedia=function(a,b){if(!u||ha||!aa)return!1;if("title"==a){var f;for(f=0;f<P;f++)if(b==V[f].data.title){b=f;var r=!0;break}if(!r)return alert('Track with title "'+b+'" doesnt exist. LoadMedia failed.'),!1}else if("counter"==a){if(0>b||b>P-1)return alert('Invalid track number. Track number  "'+b+'" doesnt exist. LoadMedia failed.'),!1}else if("id"==a&&(f=U.find(".awp-playlist-item[data-media-id="+
b+"]"),b=U.children(".awp-playlist-item").index(f),void 0==b||!b||-1==b))return alert("No media with ID to load! LoadMedia failed."),!1;w.processPlaylistRequest(b)};this.loadPlaylist=function(a){if(!u||ha)return!1;if("undefined"===typeof a||AWPUtils.isEmpty(a))return alert("loadPlaylist method requires id parameter. loadPlaylist failed."),!1;if(Ba==a)return!1;Ba=a;I(Ba)};this.addTrack=function(a,b,f,r){if(!u||ha)return!1;if("undefined"===typeof a)return alert("addTrack method requires format parameter. AddTrack failed."),
!1;if("undefined"===typeof b)return alert("addTrack method requires track parameter. AddTrack failed."),!1;Ma=!1;"undefined"!==typeof f&&(Ma=f);f=1;var x=!1;if("string"!==typeof b&&"[object Object]"!==Object.prototype.toString.call(b))if("[object Array]"===Object.prototype.toString.call(b))f=b.length,x=!0;else return alert("addTrack method requires track as string, object or array parameter. AddTrack failed."),!1;X=r;za=!1;ma=!0;if(aa)if("undefined"!==typeof X){if(0>X||X>P)return alert('Invalid position to insert track to. Position number "'+
r+'" doesnt exist. AddTrack failed.'),!1;X==P&&(za=!0)}else za=!0,X=P;else{if("undefined"!==typeof X){if(0!=X)return alert('Invalid position to insert track to. Position number "'+r+'" doesnt exist. AddTrack failed.'),!1}else X=0;za=!0}ha=!0;Bb();Va=!1;nb=!0;ya=-1;ia=[];la=[];for(r=0;r<f;r++){var D=x?b[r]:b;if("html"==a){D=g(D);var S=g("<div>").append(D.clone()).html();D=document.createElement("div");D.innerHTML=S;D=g(D.firstChild);D=G(D)}la.push(D)}P=la.length;La=!1;aa||(La=!0);aa=U;B()};this.inputAudio=
function(a){if(!u||ha)return!1;if("undefined"===typeof a)return alert("inputAudio method requires data parameter. inputAudio failed."),!1;v();w.reSetCounter();C=a;W="audio";void 0!=C.title&&vb(J.getTitleFormatted(C));if(void 0!=C.thumb&&(a=a.thumb||a.thumbDefault,bb.length&&"undefined"!==typeof a)){bb.empty();var b=new Image;b.className="awp-hidden";b.onload=function(){this.className="awp-visible"};b.src=a;bb[0].appendChild(b)}Ka&&(ta=!0);E()};this.removeTrack=function(a){if(!u||ha||!aa)return!1;
if("undefined"===typeof a)return alert("removeTrack method requires id parameter. removeTrack failed."),!1;if("string"===typeof a){var b,f=!1;for(b=0;b<P;b++)if(a==V[b].data.title){a=b;f=!0;break}if(!f)return alert('Track with title "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else if("number"===typeof a){if(a=parseInt(a,10),0>a||a>P-1)return alert('Invalid id number. Track number  "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else return alert("removeTrack method requires either a id number or a track title to remove. removeTrack failed."),
!1;V[a]?(U.children(".awp-playlist-item").eq(a).remove(),V.splice(a,1),L(),0<P?(b=w.getCounter(),a==b?($a(),w.setPlaylistItems(P)):(w.setPlaylistItems(P,!1),a<b&&w.reSetCounter(w.getCounter()-1)),-1!=w.getCounter()?(ja=w.getCounter(),vb(ja)):"undefined"!==typeof awpMediaEmpty&&awpMediaEmpty(J,R)):kb()):alert('RemoveTrack with id "'+a+'" failed.')};this.sort=function(a,b){if(!u||!aa)return!1;if("undefined"===typeof a)return console.log("Sort method requires type parameter. Sort method failed."),!1;
var f=U.children("div.awp-playlist-item"),r=f.length,x=a.toLowerCase();if(2>r)return!1;if("title"==x)for(AWPUtils.keysrt2(V,"data","title_full",b||!1),r=[],x=0;x<P;x++)r.push(V[x].id);else if("random"==x)r=AWPUtils.randomiseArray(r),V=AWPUtils.sortArray(V,r);else return console.log("Sort method requires type parameter. Sort method failed."),!1;x=w.getCounter();U.append(g.map(r,function(D){return f[D]}));-1!=x&&(r=U.children("div.awp-playlist-item[data-id='"+x+"']").index(),w.reSetCounter(r),ja=r);
L()};this.destroyMedia=function(){if(!u)return!1;Lb()};this.destroyPlaylist=function(){if(!u||!aa)return!1;kb()};this.destroyPlugin=function(){if(!u)return!1;Lb();"undefined"!==typeof l&&l.destroy()};this.setPlaybackRate=function(a){if(!u||"undefined"!==typeof w&&-1==w.getCounter())return!1;"undefined"!==typeof l&&l.setPlaybackRate(a)};this.toggleRandom=function(a){if(!u||"undefined"===typeof w)return!1;da="undefined"!==typeof a?a:!da;w.setRandom(da);da?wa.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):
wa.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")};this.toggleLoop=function(a){if(!u||"undefined"===typeof w)return!1;ca="undefined"!==typeof a?a:!ca;w.setLooping(ca);ca?va.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):va.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")};this.setVolume=function(a){if(!u)return!1;0>a?a=0:1<a&&(a=1);M=a;h()};this.getVolume=function(){return u?M:!1};this.toggleMute=function(){if(!u)return!1;
c()};this.seek=function(a){if(!u||!W)return!1;"undefined"!==typeof l&&l.seekTo(a/l.getDuration())};this.seekBackward=function(a){if(!u||!W)return!1;a=a||H.seekTime;a=parseInt(a,10);"undefined"!==typeof l&&(a=Math.max(l.getCurrentTime()-a,0),l.seekTo(a))};this.seekForward=function(a){if(!u||!W)return!1;a=a||H.seekTime;a=parseInt(a,10);"undefined"!==typeof l&&(a=Math.min(l.getCurrentTime()+a,l.getDuration()),l.seekTo(a))};this.getCurrentTime=function(){if(!u||!W)return!1;var a;"undefined"!==typeof l&&
(a=l.getCurrentTime());return a};this.getDuration=function(){if(!u||!W)return!1;var a;"undefined"!==typeof l&&(a=l.getDuration());return a};this.initPlaylistScroll=function(a){if(!u)return!1;oa(a)};this.destroyPlaylistScroll=function(){if(!u)return!1;ua.mCustomScrollbar("destroy");Ya=!1};this.updatePlaylistScroll=function(){if(!u)return!1;ua.mCustomScrollbar("update")};this.setAutoPlay=function(a){if(!u)return!1;ta=a};this.getSetupDone=function(){return u};this.getPlaylistTransition=function(){return ha};
this.getPlaylistLoaded=function(){return Va};this.getMediaPlaying=function(){return u?Y:!1};this.getActiveItemId=function(){return u?"undefined"!==typeof w?w.getCounter():null:!1};this.getPlaylistLength=function(){return u?AWPUtils.isNumber(P)?P:0:!1};this.getPlaylistItems=function(){if(!u)return!1;var a=[];U.find("div.awp-playlist-item").each(function(){a.push(g(this))});return a};this.getPlaylistData=function(){return V||null};this.getCurrMediaData=function(){return u?C:!1};this.getTitle=function(a){return Ga(a)};
this.getSettings=function(){return u?H||null:!1};this.getInstanceName=function(){return u?R:!1};this.toggleInteraction=function(){"undefined"!==typeof l&&l.toggleInteraction()};this.overControls=function(a){y(a)};this.outControls=function(a){p(a)};this.showPlayerElements2=function(){showPlayerElements2()};AWPUtils.isEmpty(Ba)?Da():I(Ba);return this}})(jQuery);